import Image from "next/image";
import Head from "next/head";
import axios from "axios";
import ParentListAndLive from "../components/ParentListAndLive";

export default function Home() {
  const apiUrl = process.env.NEXT_PUBLIC_FLASK_API_URL;
  return (
    <div>
      <Head>
        <title>Crypto-checker</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Overlay */}
      <div className="absolute top-0 left-0 right-0 bottom-0 bg-white/10 z-[1]" />

      {/* Background Image */}
      <Image
        src="https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y3J5cHRvfGVufDB8fDB8fHww&auto=format&fit=crop&w=1000&q=60"
        className="object-cover"
        fill={true}
        alt=""
      />

      <div className="relative flex justify-between items-center max-w-[600px] w-full m-auto pt-4 text-white z-10 ">
        <ParentListAndLive />
      </div>
    </div>
  );
}
